#pragma once

#define ORTHIA_UI_VER_MAJOR        1
#define ORTHIA_UI_VER_MAJOR_STR   "1"

#define ORTHIA_UI_VER_MINOR        1
#define ORTHIA_UI_VER_MINOR_STR   "1"

#define ORTHIA_UI_VER_PATCH        0
#define ORTHIA_UI_VER_PATCH_STR   "0"

#define ORTHIA_UI_VER_REVISION        8
#define ORTHIA_UI_VER_REVISION_STR   "8"

#define ORTHIA_UI_VERSION  ORTHIA_UI_VER_MAJOR_STR "." ORTHIA_UI_VER_MINOR_STR "." ORTHIA_UI_VER_PATCH_STR "." ORTHIA_UI_VER_REVISION_STR 
